version: "3.8"

services:
  mongodb:
    image : mongo
    container_name: mongodb-stolen-bikes-platform
    environment:
    - PUID=1000
    - PGID=1000
    volumes:
    - /your/path/to/db/:/data/db
    ports:
    - "27017:27017"
    restart: unless-stopped